AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - "lib/any_sms/backend/aws/version.rb"
    - "lib/any_sms-backend-aws.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Max: 90

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
